### ISSUE TITLE
상품 엔티티 정의하기

### ISSUE THREAD

**Issue by SeungGun** [SeungGun/ASGS_Backend#10]
## Task List
- [x] 카테고리 엔티티 정의
- [x] 상품 엔티티 정의
- [x] 상품 이미지 엔티티 정의
