### ISSUE TITLE
[MENU] 상세 메뉴 조회 API 구현

### ISSUE THREAD

**Issue by SeungGun** [SeungGun/ASGS_Backend#19]
## Task List
- [ ] 메뉴 ID로 조회
- [ ] 이미지 데이터 함께 조회
- [ ] 옵션 데이터 함께 조회
