### ISSUE TITLE
[USER] 유저 엔티티 정의

### ISSUE THREAD

**Issue by SeungGun** [SeungGun/ASGS_Backend#2]
## Task List
- [x] Base Entity 정의
- [x] 유저 엔티티 정의
- [x] 유저 ROLE 정의
- [x] 유저 STATUS 정의
