### ISSUE TITLE
[CART] 장바구니 엔티티 정의

### ISSUE THREAD

**Issue by SeungGun** [SeungGun/ASGS_Backend#44]
## Task List
- [ ] 장바구니 엔티티 정의
- [ ] 메뉴 엔티티와 매핑
- [ ] 메뉴 옵션 매핑
