### ISSUE TITLE
초기 엔티티 수정하기

### ISSUE THREAD

**Issue by SeungGun** [SeungGun/ASGS_Backend#9]
## Task List
- [x] User 엔티티 nullable 처리 수정
- [x] User 엔티티에 UserRole 필드 추가
- [x] BaseEntity create, modify 대상 컬럼 추가
